### ISSUE TITLE
TrakEM2 <-> render Import/Export

### ISSUE THREAD

**Issue by unidesigner** [saalfeldlab/render#101]
Hi! I'm trying to understand what would be the best options to export a TrakEM2 project to render and vice-versa. I found the [TrakEM2](https://github.com/saalfeldlab/render/tree/master/trakem2-scripts) scripts folder, but I have some problem how to setup/use those scripts. I could not find any documentation. Would you be able to point into the right direction? Thanks.

**Comment by trautmane** [comment]
Hi Stephan - Converting between TrakEM2 and Render is possible but (as you noted) not documented.  I'm currently on holiday, but will return Friday and can write something up for you then.  Let me know if waiting until Friday is a problem and I can adjust. --Eric

**Comment by unidesigner** [comment]
Hi Eric! I can surely wait until Friday or next week, no problem. Enjoy your holidays! Stephan

**Comment by trautmane** [comment]
Hi Stephan,  The TrakEM2 plugin I have for exporting from TrakEM2 to render-ws contains a hack-y workaround to handle lens correction transforms which are shared in render-ws (e.g. for tiles imaged by the same camera) but are copied in TrakEM2.  Does the data you need to export from TrakEM2 contain shared transforms or does each patch have a unique list of transforms?

**Comment by unidesigner** [comment]
Hi Eric, it does not contain any shared transform and each patch has a unique list of transforms. I also tried the BeanShell script in the repository, but could not make it work (some error with missing javac).

**Comment by trautmane** [comment]
Thanks Stephan - I'd like to create a variant of the export plugin that will suit your purposes better.  It probably won't be ready until late on Friday, July 5th.  Let me know if waiting until then is a problem for you.  After I'm done with the first draft, we will probably need to iterate a few times through your use case to make sure the plugin works for you.

**Comment by unidesigner** [comment]
Friday, July 5th is good for me, thanks.

**Comment by trautmane** [comment]
Stephan - take a look at https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/trakem2-scripts.md and let me know if (a) things make sense and (b) the plugin(s) work for you.  I suspect we'll need to iterate on this a bit to get it right for you.

**Comment by unidesigner** [comment]
Thanks, Eric. The plugin works great! I'll let you know if I run into issues.
