### ISSUE TITLE
JETTY_VERSION 9.3.7.v20160115 no longer exists

### ISSUE THREAD

**Issue by perlman** [saalfeldlab/render#11]
The download for Jetty 9.3.7.v20160115 no longer works.

This is from /render-ws/src/main/scripts/install.sh:
...
JETTY_VERSION="9.3.7.v20160115"
JETTY_DIST="jetty-distribution-${JETTY_VERSION}"
...
JETTY_URL="http://download.eclipse.org/jetty/${JETTY_VERSION}/dist/${JETTY_DIST}.tar.gz"

Minimally, the version should be updated.  Ideally, is there a way to link to a 'current' version (or use maven in some form for a reliable archive?)

**Comment by alexbaden** [comment]
It appears that eclipse deprecated that URL. There is a maven equivalent:

http://central.maven.org/maven2/org/eclipse/jetty/jetty-distribution/9.3.7.v20160115/jetty-distribution-9.3.7.v20160115.tar.gz
