### ISSUE TITLE
Cross-Correlation Client problem

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#112]
Hi,

I run into an error using https://github.com/saalfeldlab/render/blob/geometric_descriptor/render-ws-java-client/src/main/java/org/janelia/render/client/CrossCorrelationPointMatchClient.java .

```
12:04:18.752 [main] INFO  [org.janelia.render.client.CrossCorrelationPointMatchClient] generateMatchesForPairFile: pairJsonFileName is /g/emcf/schorb/render-output/tile_pairs_giovanna1_mipmap_z_123_to_234_dist_0.json
12:04:18.756 [main] INFO  [org.janelia.alignment.match.RenderableCanvasIdPairs] load: entry, path=/g/emcf/schorb/render-output/tile_pairs_giovanna1_mipmap_z_123_to_234_dist_0.json
12:04:18.855 [main] INFO  [org.janelia.alignment.match.RenderableCanvasIdPairs] load: exit, loaded 2519 pairs
12:04:18.860 [main] INFO  [org.janelia.alignment.match.CanvasRenderParametersUrlTemplate] getTemplateForRun: returning http://pc-emcf-16:8080/render-ws/v1/owner/SBEM/project/tests/stack/giovanna1_mipmap/tile/{id}/render-parameters?scale=1.0&filter=true&excludeMask=true&normalizeForMatching=true
12:04:18.900 [main] INFO  [org.janelia.render.client.CrossCorrelationPointMatchClient] generateMatchesForPairs: derive matches between {canvasId: '0000.0110.00123::TOP', url: 'http://pc-emcf-16:8080/render-ws/v1/owner/SBEM/project/tests/stack/giovanna1_mipmap/tile/0000.0110.00123/render-parameters?scale=1.0&filter=true&excludeMask=true&normalizeForMatching=true'} and {canvasId: '0000.0125.00123::BOTTOM', url: 'http://pc-emcf-16:8080/render-ws/v1/owner/SBEM/project/tests/stack/giovanna1_mipmap/tile/0000.0125.00123/render-parameters?scale=1.0&filter=true&excludeMask=true&normalizeForMatching=true'}
12:04:18.902 [main] INFO  [org.janelia.alignment.RenderParameters] loadFromUrl: loading http://pc-emcf-16:8080/render-ws/v1/owner/SBEM/project/tests/stack/giovanna1_mipmap/tile/0000.0110.00123/render-parameters?scale=1.0&filter=true&excludeMask=true&normalizeForMatching=true
12:04:19.046 [main] INFO  [org.janelia.alignment.match.CanvasIdWithRenderContext] loadRenderParameters: loaded 0000.0110.00123::TOP
12:04:19.109 [main] DEBUG [org.janelia.alignment.util.ImageProcessorCache] loadImageProcessor: entry, urlString=file:///g/emcf/ronchi/Benvenuto-Giovanna-seaurchin_SBEMtest_5833/giovanna_G3-1_20-07-07_3view/S010_acquisition/tiles/g0000/t0110/S010_acquisition_g0000_t0110_s00123.tif, downSampleLevels=0
12:04:19.219 [main] DEBUG [org.janelia.alignment.mipmap.UrlMipmapSource] getChannels: tile '0000.0110.00123' took 117 milliseconds to load level 0 (first mip:117, downSampleLevels:0, first mask:0, additional channels:0), cacheSize:1
12:04:19.419 [main] DEBUG [org.janelia.alignment.mipmap.FilteredMipmapSource] getChannels: filtered tile '0000.0110.00123' took 196 milliseconds to filter level 0
12:04:19.442 [main] DEBUG [org.janelia.alignment.mipmap.RenderedCanvasMipmapSource] mapPixels: mapping of filtered tile '0000.0110.00123' took 22 milliseconds to process (mesh:19, map interpolated:3)
12:04:19.442 [main] DEBUG [org.janelia.alignment.mipmap.RenderedCanvasMipmapSource] getChannels: deriving average scale for 1 canvases took 3 milliseconds
12:04:19.442 [main] INFO  [org.janelia.alignment.RenderParameters] loadFromUrl: loading http://pc-emcf-16:8080/render-ws/v1/owner/SBEM/project/tests/stack/giovanna1_mipmap/tile/0000.0125.00123/render-parameters?scale=1.0&filter=true&excludeMask=true&normalizeForMatching=true
12:04:19.452 [main] INFO  [org.janelia.alignment.match.CanvasIdWithRenderContext] loadRenderParameters: loaded 0000.0125.00123::BOTTOM
12:04:19.462 [main] DEBUG [org.janelia.alignment.util.ImageProcessorCache] loadImageProcessor: entry, urlString=file:///g/emcf/ronchi/Benvenuto-Giovanna-seaurchin_SBEMtest_5833/giovanna_G3-1_20-07-07_3view/S010_acquisition/tiles/g0000/t0125/S010_acquisition_g0000_t0125_s00123.tif, downSampleLevels=0
12:04:19.534 [main] DEBUG [org.janelia.alignment.mipmap.UrlMipmapSource] getChannels: tile '0000.0125.00123' took 72 milliseconds to load level 0 (first mip:72, downSampleLevels:0, first mask:0, additional channels:0), cacheSize:2
12:04:19.640 [main] DEBUG [org.janelia.alignment.mipmap.FilteredMipmapSource] getChannels: filtered tile '0000.0125.00123' took 106 milliseconds to filter level 0
12:04:19.651 [main] DEBUG [org.janelia.alignment.mipmap.RenderedCanvasMipmapSource] mapPixels: mapping of filtered tile '0000.0125.00123' took 11 milliseconds to process (mesh:11, map interpolated:0)
12:04:19.651 [main] DEBUG [org.janelia.alignment.mipmap.RenderedCanvasMipmapSource] getChannels: deriving average scale for 1 canvases took 1 milliseconds
12:04:19.651 [main] INFO  [org.janelia.alignment.match.CanvasCorrelationMatcher] deriveMatchResult: entry
12:04:19.653 [main] ERROR [org.janelia.render.client.ClientRunner] run: caught exception
java.lang.NullPointerException: null
	at org.janelia.alignment.match.parameters.CrossCorrelationParameters.getScaledSampleSize(CrossCorrelationParameters.java:63)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.getCandidateMatches(CanvasCorrelationMatcher.java:97)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.deriveMatchResult(CanvasCorrelationMatcher.java:79)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.deriveMatchResult(CanvasCorrelationMatcher.java:60)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.generateMatchesForPairs(CrossCorrelationPointMatchClient.java:220)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.generateMatchesForPairFile(CrossCorrelationPointMatchClient.java:133)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.access$100(CrossCorrelationPointMatchClient.java:44)
	at org.janelia.render.client.CrossCorrelationPointMatchClient$1.runClient(CrossCorrelationPointMatchClient.java:98)
	at org.janelia.render.client.ClientRunner.run(ClientRunner.java:38)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.main(CrossCorrelationPointMatchClient.java:104)
12:04:19.654 [main] INFO  [org.janelia.render.client.ClientRunner] run: exit, processing failed after 0 hours, 0 minutes, 1 seconds
```

The tile pair file looks OK to me. Am I missing something?
I called:
```
java -cp render-ws-java-client-2.3.1-SNAPSHOT-standalone.jar org.janelia.render.client.CrossCorrelationPointMatchClient  --baseDataUrl http://pc-emcf-16:8080/render-ws/v1 --owner SBEM --collection Xcorrtest1 --pairJson /g/emcf/schorb/render-output/tile_pairs_giovanna1_mipmap_z_123_to_234_dist_0.json 
```
So for the rest I tried with the default parameters to start with.

**Comment by trautmane** [comment]
I'm guessing you are missing --ccFullScaleSampleSize.  Looks like I missed marking --ccFullScaleSampleSize, --ccFullScaleStepSize, and --ccMinResultThreshold as required parameters.  

You can find example values here:
https://github.com/saalfeldlab/render/blob/geometric_descriptor/render-app/src/test/java/org/janelia/alignment/match/CrossCorrelationTest.java#L101-L103

I'll fix this issue later today by making those parameters as required.

**Comment by martinschorb** [comment]
still...

```
12:53:37.533 [main] ERROR [org.janelia.render.client.ClientRunner] run: caught exception
java.lang.NullPointerException: null
	at org.janelia.alignment.match.CanvasCorrelationMatcher.findRectangle(CanvasCorrelationMatcher.java:203)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.getCandidateMatches(CanvasCorrelationMatcher.java:100)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.deriveMatchResult(CanvasCorrelationMatcher.java:79)
	at org.janelia.alignment.match.CanvasCorrelationMatcher.deriveMatchResult(CanvasCorrelationMatcher.java:60)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.generateMatchesForPairs(CrossCorrelationPointMatchClient.java:220)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.generateMatchesForPairFile(CrossCorrelationPointMatchClient.java:133)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.access$100(CrossCorrelationPointMatchClient.java:44)
	at org.janelia.render.client.CrossCorrelationPointMatchClient$1.runClient(CrossCorrelationPointMatchClient.java:98)
	at org.janelia.render.client.ClientRunner.run(ClientRunner.java:38)
	at org.janelia.render.client.CrossCorrelationPointMatchClient.main(CrossCorrelationPointMatchClient.java:104)
12:53:37.534 [main] INFO  [org.janelia.render.client.ClientRunner] run: exit, processing failed after 0 hours, 0 minutes, 1 seconds
```

with calling

```
$java -cp render-ws-java-client-2.3.1-SNAPSHOT-standalone.jar org.janelia.render.client.CrossCorrelationPointMatchClient  --baseDataUrl http://pc-emcf-16:8080/render-ws/v1 --owner SBEM --collection Xcorrtest1 --pairJson /g/emcf/schorb/render-output/tile_pairs_giovanna1_mipmap_z_123_to_234_dist_0.json --ccFullScaleSampleSize 250  --ccFullScaleStepSize 5 --ccMinResultThreshold 0.5
```

**Comment by trautmane** [comment]
Ok - that's a different problem.  Looks like Preibisch didn't account for tiles without masks (and I didn't catch it).  I'll get you a fix shortly ...

**Comment by martinschorb** [comment]
I tested the new client and it runs.

However, it seems to not find any useful CC. All I get is hits with no shift...

```
12:42:33.471 [main] DEBUG [org.janelia.alignment.match.CanvasCorrelationMatcher] getCandidateMatches: renderScale=1.0, minResultThreshold=0.5, scaledSampleSize=250, scaledStepSize=5, numTests=361, stepIncrement=4.9944598337950135
12:42:35.570 [main] DEBUG [org.janelia.alignment.match.CanvasCorrelationMatcher] 0 > 249, shift : (0.0, 0.0), correlation (R)=1.0
12:42:37.063 [main] DEBUG [org.janelia.alignment.match.CanvasCorrelationMatcher] 5 > 254, shift : (0.0, 0.0), correlation (R)=1.0

...
```

Any idea what could be the reason? I tried with different `SampleSize` and `scaledStepSize`.

**Comment by trautmane** [comment]
I might be able to get Preibisch to help.  Can you send me (or give me access to) the 2 source images and their json tile specs?

**Comment by martinschorb** [comment]
Here we go:

https://oc.embl.de/index.php/s/D8QsCaK2KBhlX7I

**Comment by trautmane** [comment]
Thanks Martin,

The first thing I noticed is that your tile specs have a 15x scaling transform appended, so I removed those transforms.
Here are the tiles I imported and an example modified tile spec:

<img width="968" alt="embl-tile-spec-fix" src="https://user-images.githubusercontent.com/4457104/98718686-bc6aa080-235c-11eb-9986-d4978fe6f393.png">
 
What is the purpose of the 15x transform?

**Comment by trautmane** [comment]
Because your tiles have plenty of tissue in the overlap area, I thought I'd try generating SIFT matches first.
Here are the results from 2 trials, a fast one at renderScale 0.4 and a slower one at renderScale 1.0 (note that I should have increased the maxEpsilon for the 1.0 trial).

<img width="2021" alt="embl-sift" src="https://user-images.githubusercontent.com/4457104/98719788-2df71e80-235e-11eb-8e66-b2ea7ae26ed0.png">

**Comment by trautmane** [comment]
I then tried adding Geometric Descriptor matching to the fast SIFT to see if it would pick up anything in the resin area:

<img width="1127" alt="embl-sift-plus-gc" src="https://user-images.githubusercontent.com/4457104/98730233-fd1ce680-2369-11eb-8858-fb41ee595bf4.png">

**Comment by trautmane** [comment]
Normally, I'd consider any of these trial results sufficient so I wouldn't use cross correlation here.  But I tried it anyway just to see if I would run into the same problem as you.  It seemed to work:

<img width="1887" alt="embl-cc-test" src="https://user-images.githubusercontent.com/4457104/98730761-baa7d980-236a-11eb-939b-c842b227fe0a.png">

Let me know what you think after looking at all of this.  I did not bother Preibisch about cross correlation parameters yet since he's very busy - but I can do that if necessary (and I already have this example imported, so it would be relatively easy for him to look at it).

**Comment by martinschorb** [comment]
Hi Eric,

> The first thing I noticed is that your tile specs have a 15x scaling transform appended, so I removed those transforms.

> What is the purpose of the 15x transform?

this is the pixel size.
It seems I still do not get it right to which spec gets pixel dimensions and which gets physical coordinates (nm).

this is how I have it now:

- `stageX` this is physical Iassume

- `minX` etc. is pixels

- `width, height` is pixels

- then there's `stack ResolutionX/Y/Z`, I guess this needs to be the same as the tileId `pixelsize`?

**Comment by trautmane** [comment]
Hi Martin,

Everything is pixels except for stack resolution.

- The `layout` data like `stageX` and `stageY` is intended to track the original pixel location "estimated" by the acquisition system.  The `sectionId` value normally tracks the original z.  All `layout` data elements should remain immutable after initial import.
- The `width` and `height` values should reflect the pixel size of the original source image and should remain immutable after initial import.
- The bounding box values (`minX`, `minY`, `maxX`, `maxY`) reflect the pixel bounds of the tile in world space after all transformations have been applied to the tile.  These values (typically) should not be explicitly specified and are derived/calculated by render-ws when you import tile specs.
- The `stackResolutionX/Y/Z` values identify pixels per nm in each dimension.  They are not needed or used by render for anything.  However, they can be useful to other clients like viewers (e.g. CATMAID or neuroglancer) that have physical dimension scale bars in their UIs.

Hope this helps,
Eric

**Comment by trautmane** [comment]
It looks like `pixelsize` is something @fcollman added to the python client (https://github.com/AllenInstitute/render-python/blob/master/renderapi/layout.py#L52-L55).  That attribute is not supported/persisted by the core render-ws.  I'm not sure if the Allen Institute uses it in some other way.
