### ISSUE TITLE
Tilepair client, something is happening at one specific section

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#113]
Hi,

when running the tilepair client (through the Python API), I run into a problem, that at some point in the stack the client writes a JSON file.

```
16:39:54.208 [main] INFO  [org.janelia.render.client.RenderDataClient] getTileBounds: submitting GET http://pc-emcf-16.embl.de:8080/render-ws/v1/owner/SBEM/project/seaurchin_paolo_test/stack/giovanna_test0_mipmaps/z/1274.0/tileBounds
16:39:54.210 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] constructed tree for 49 tiles
16:39:54.210 [main] INFO  [org.janelia.render.client.TilePairClient] buildRTree: added bounds for 49 out of 49 tiles for z 1274.0
16:39:54.211 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: entry, checking 49 tiles with z 1274.0, 0 neighborTrees, firstTileId is 0000.0064.01274
16:39:54.211 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: exit, returning 116 pairs
16:39:54.211 [main] INFO  [org.janelia.render.client.RenderDataClient] getTileBounds: submitting GET http://pc-emcf-16.embl.de:8080/render-ws/v1/owner/SBEM/project/seaurchin_paolo_test/stack/giovanna_test0_mipmaps/z/1275.0/tileBounds
16:39:54.213 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] constructed tree for 49 tiles
16:39:54.213 [main] INFO  [org.janelia.render.client.TilePairClient] buildRTree: added bounds for 49 out of 49 tiles for z 1275.0
16:39:54.213 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: entry, checking 49 tiles with z 1275.0, 0 neighborTrees, firstTileId is 0000.0064.01275
16:39:54.213 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: exit, returning 116 pairs
16:39:54.807 [main] INFO  [org.janelia.alignment.util.FileUtil] saveJsonFile: exit, wrote data to /g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p000.json
16:39:54.808 [main] INFO  [org.janelia.render.client.RenderDataClient] getTileBounds: submitting GET http://pc-emcf-16.embl.de:8080/render-ws/v1/owner/SBEM/project/seaurchin_paolo_test/stack/giovanna_test0_mipmaps/z/1276.0/tileBounds
16:39:54.813 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] constructed tree for 49 tiles
16:39:54.814 [main] INFO  [org.janelia.render.client.TilePairClient] buildRTree: added bounds for 49 out of 49 tiles for z 1276.0
16:39:54.814 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: entry, checking 49 tiles with z 1276.0, 0 neighborTrees, firstTileId is 0000.0064.01276
16:39:54.814 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] getCircleNeighbors: exit, returning 116 pairs
16:39:54.815 [main] INFO  [org.janelia.render.client.RenderDataClient] getTileBounds: submitting GET http://pc-emcf-16.embl.de:8080/render-ws/v1/owner/SBEM/project/seaurchin_paolo_test/stack/giovanna_test0_mipmaps/z/1277.0/tileBounds
16:39:54.820 [main] DEBUG [org.janelia.alignment.spec.TileBoundsRTree] constructed tree for 49 tiles
```

At `z=1276` there is a single 

```
6:39:54.807 [main] INFO  [org.janelia.alignment.util.FileUtil] saveJsonFile: exit, wrote data to /g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p000.json
```

- Is this intentional behavior? The sections around that value all look normal.
- Does it just split the output JSON to separate files once a certain file size is exceeded? 
- How Do I then pass the tilepair JSON file on to the downstream clients if it is no longer a single file?
- The Python caller fails as it no longer finds the file...

https://github.com/AllenInstitute/render-python/blob/7208b41f1bc14bc3f027e8553d8fabcbb2cfc572/renderapi/client/client_calls.py#L231

https://github.com/AllenInstitute/render-python/issues/150

**Comment by trautmane** [comment]
Hi Martin,

The tile pair client supports a `--maxPairsPerFile` parameter that has a default value of 100000.  This is allows other clients that process the pairs (like the SIFT point match clients) to ingest the pairs in batches instead of needing to read them all in at once.  When you get into many millions of pairs for larger data sets, chunking them into separate files is useful.  Chunking the pairs also helps with array jobs if you are using that style of parallelization instead of spark since you can assign different files to different jobs.

Clients that take tile pair json files as input allow you to specify multiple files (e.g. `--pairJson p000.json --pairJson p001.json`).

During pair generation, if the number of pairs exceeds maxPairsPerFile, the pair client starts saving to a new file `...p[n+1]`.

I added `--maxPairsPerFile` support to the tile pair client in October 2017.
@RussTorres setup the corresponding render python wrapper earlier that year in February (see https://github.com/AllenInstitute/render-python/blame/7208b41f1bc14bc3f027e8553d8fabcbb2cfc572/renderapi/client/client_calls.py#L231), so it looks like the wrapper never got updated.

**Comment by trautmane** [comment]
<img width="1740" alt="Screen Shot 2020-11-23 at 9 05 42 PM" src="https://user-images.githubusercontent.com/4457104/100037276-ca460a00-2dcf-11eb-8928-70e2dea89f59.png">

**Comment by martinschorb** [comment]
OK,
 I have a temporary workaround by adding this parameter and then simply ignoring the single output file in the Python wrapper.

Now, when I want to run the SIFTPointMatchCLient, it has exactly the same problem of not being able to find the file.

```
java.io.FileNotFoundException: /g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_2348_dist_0.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at org.janelia.alignment.util.FileUtil.getExtensionBasedReader(FileUtil.java:57)
	at org.janelia.alignment.match.RenderableCanvasIdPairs.load(RenderableCanvasIdPairs.java:86)
	at org.janelia.render.client.spark.SIFTPointMatchClient.generateMatchesForPairFile(SIFTPointMatchClient.java:139)
	at org.janelia.render.client.spark.SIFTPointMatchClient.run(SIFTPointMatchClient.java:127)
	at org.janelia.render.client.spark.SIFTPointMatchClient$1.runClient(SIFTPointMatchClient.java:94)
	at org.janelia.render.client.ClientRunner.run(ClientRunner.java:38)
	at org.janelia.render.client.spark.SIFTPointMatchClient.main(SIFTPointMatchClient.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	...
```

How do I need to provide the tilepair files as parameters?
Does `--pairJson` accept comma-separated listings of the multiple tilepair files?

**Comment by trautmane** [comment]
Hi Martin,

If you look in `/g/emcf/schorb/render-output/tile` you should see the actual chunked json files.

You listed the first one in your post above:
`/g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p000.json`

After that, you should see:
`/g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p001.json`
...
`/g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p<n>.json`

For the SIFTPointMatchClient, you specify each file you want to process with:
`--pairJson /g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p000.json --pairJson /g/emcf/schorb/render-output/tile_pairs_giovanna_test0_mipmaps_z_0_to_1280_dist_0_p001.json ...`

It doesn't currently accept comma separated values.

My match client call scripts typically have something like this:
```
for JSON_FILE in `ls ${PAIRS_DIR}/tile_pairs_*.json*`; do
  ARGS="${ARGS} --pairJson ${JSON_FILE}"
done
```

**Comment by RussTorres** [comment]
I have a render-python PR and tests in which I expand the functionality of this -- it will automatically build a python dictionary from the multiple files and optionally return a list of the generated files.  This should now be consistent with the old implementation when used for large numbers of pairs, but gives the option to move on using the split files.

We didn't start render-python with the plan of mapping 1:1 with render's functionality, but we have solid use cases for most of the features so it has organically gotten pretty close.  I hadn't noticed this change, but happy to add support.

**Comment by trautmane** [comment]
Thanks Russel!
