### ISSUE TITLE
Match Trial hand over parameters

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#117]
Hi,

my current strategy for finding good SIFT parameters for a new experiment is to look in a table of specimens and then open an existing successful match trial applying it to a new stack.

So far, I need to open an existing trial, click `Create new Trial` and then manually type (copy&paste) the new tile parameter URLs into the web form.

Would it be a lot of modification to enable additional parameter passing to `match-trial.html?matchTrialId=TBD` ?

- Something like `TrialTemplateID` and the ID of the template to pre-fill this form with the `featureAndMatchParameters` of that Trial entry?
- Or maybe an option to pass the individual parameters 
- Ideally, I would just pass  the whole MatchTrial JSON `parameters` (without `matches`and `stats`) including also `pRenderParametersUrl` and `qRenderParametersUrl`

Knowing your skills, this is likely already possible and I just could not get my parameters in there the correct way...

Happy New Year BTW

**Comment by trautmane** [comment]
Happy New Year Martin!

To make sure I understand, is your goal simply to remove the need to click "Create new Trial" ?

**Comment by martinschorb** [comment]
Hi Eric,

in order to run a new MatchTrial I need to provide:
- the `featureAndMatchParameters` , I want to use those from an existing MatchTrial (clicking the button "Create new Trial" will do this)
- provide the render parameter URL for both tiles to try (these now will be from a different stack compared to the existing template Trial)

I would love to have a way to provide both the starting parameters as well as the (new) tile URLs in one go and thought of passing them as query strings in the URL.

I noticed that 
```
.../match-trial.html?matchTrialId=TBD&iterations=200&maxEpsilon=4&pRenderParametersUrl=https%3A%2F%2Fgoogle.com%0A
```

This works for `pRenderParametersUrl` and `qRenderParametersUrl` but I cannot get the other parameters to fill the form.

Ideally I could do this all at once by just providing the template MatchTrial ID

**Comment by trautmane** [comment]
Thanks - I understand.  That should be fairly easy to do.  I'll take a closer look and let you know how it goes ...
