### ISSUE TITLE
Tilepair client excludeCornerNeighbors

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#119]
Hi,

whenever I run the tilepair client across layers, I end up with corner pairs. This seems to happen regardless of whether or how the parameter `excludeCornerNeighbors` is set.

When I run the client without that parameter, I expect it to default to `True` and I can exclude any typos etc. on my side.

```
  Running: /g/emcf/software/render/deploy/jdk1.8.0_131/bin/java -cp /g/emcf/software/render/render-ws-java-client/target/render-ws-java-client-2.3.1-SNAPSHOT-standalone.jar -Xms5G -Xmx5G -Djava.awt.headless=true -XX:+UseSerialGC org.janelia.render.client.TilePairClient --baseDataUrl ...
 --minZ 0.0 --maxZ 1299.0 --xyNeighborFactor 0.9 --zNeighborDistance 1 --excludeCompletelyObscuredTiles True --excludeSameLayerNeighbors True --toJson ...


08:35:37.645 [main] INFO  [org.janelia.render.client.ClientRunner] run: entry
08:35:37.828 [main] INFO  [org.janelia.render.client.TilePairClient] runClient: entry, parameters={
  "renderWeb" : {
  ...
  },
  "xyNeighborFactor" : 0.9,
  "useRowColPositions" : false,
  "zNeighborDistance" : 1,
  "excludeCornerNeighbors" : true,
  "excludeCompletelyObscuredTiles" : true,
  "excludeSameLayerNeighbors" : true,
  "excludeSameSectionNeighbors" : false,
  "minExistingMatchCount" : 0,
  "toJson" : ...,
  "maxPairsPerFile" : 100000,
  "bounds" : { }
}
```

Still, the resulting tilepair list contains corner neighbors. Does this parameter not work when searching for pairs across layers?

**Comment by trautmane** [comment]
Hi,

It is supposed to work, but in practice we don't exclude corner neighbors for cross layer matching - so there could be a bug.  Can you post here the tile specs for one cross layer pair from your example above that should have been excluded?

**Comment by martinschorb** [comment]
Hi,

that would be for example:

p:

```
{
  "tileId": "0000.0101.00998",
  "layout": {
    "sectionId": "998",
    "temca": "3View",
    "camera": "3View",
    "stageX": -20739.3,
    "stageY": -39348.2,
    "rotation": 0,
    "pixelsize": 10
  },
  "z": 998,
  "minX": -20739,
  "minY": -39348,
  "maxX": -16643,
  "maxY": -36276,
  "width": 4096,
  "height": 3072,
  "minIntensity": 0,
  "maxIntensity": 255,
  "mipmapLevels": {
    "0": {
      "imageUrl": "file:///..."
    }
  },
  "transforms": {
    "type": "list",
    "specList": [
      {
        "type": "leaf",
        "className": "mpicbg.trakem2.transform.AffineModel2D",
        "dataString": "1.0000000000 0.0000000000 0.0000000000 1.0000000000 -20739.3000000000 -39348.2000000000"
      }
    ]
  },
  "meshCellSize": 64
}
```
q:
```
{
  "tileId": "0000.0089.00999",
  "layout": {
    "sectionId": "999",
    "temca": "3View",
    "camera": "3View",
    "stageX": -20739.3,
    "stageY": -42220.2,
    "rotation": 0,
    "pixelsize": 10
  },
  "z": 999,
  "minX": -20739,
  "minY": -42220,
  "maxX": -16643,
  "maxY": -39148,
  "width": 4096,
  "height": 3072,
  "minIntensity": 0,
  "maxIntensity": 255,
  "mipmapLevels": {
    "0": {
      "imageUrl": "file:///g/emcf/ronchi/Gross-Rahul-VMHSBEM_5799/S013_21-01-21_3view/tiles/g0000/t0089/S013_21-01-21_3view_g0000_t0089_s00999.tif"
    }
  },
  "transforms": {
    "type": "list",
    "specList": [
      {
        "type": "leaf",
        "className": "mpicbg.trakem2.transform.AffineModel2D",
        "dataString": "1.0000000000 0.0000000000 0.0000000000 1.0000000000 -20739.3000000000 -42220.2000000000"
      }
    ]
  },
  "meshCellSize": 64
}
```

**Comment by trautmane** [comment]
In this case, the code is working as designed.  These 2 tiles have the same x bounds so they are not considered "corner neighbors".  The tiles marked 'x' in this diagram are the ones the tile pair client considers corner neighbors:

<img width="338" alt="Screen Shot 2021-02-12 at 8 23 47 AM" src="https://user-images.githubusercontent.com/4457104/107773766-21db7e00-6d0c-11eb-8df1-4f456f2b332d.png">

That being said, the real intent for excluding corner neighbors was to improve same layer (montage) solves.  Khaled noticed that excluding them helped so we did.  The TEM volume we were initially reconstructing did not have tiles that naturally aligned across layers (the tile bounds between aligned layers were rarely if ever in the same place), so the concept of cross layer corners just didn't exist.

**Comment by trautmane** [comment]
If your goal is to exclude all tiles except for those directly above/below the current tile in the cross layer generation, you should split your same layer and cross layer pair generation runs into two separate steps.  Then for the cross layer run, use a very small --xyNeighborFactor or --explicitRadius value.

**Comment by martinschorb** [comment]
Hi,
OK, that indeed makes a lot of sense.
In a setup where you sequentially remove surface sections and then record tiles on each section such as in serial block face SEM with an integrated microtome or FIB-SEM, our scenario would be quite common.
During the pointmatch client run this then means, that 5x more tilepairs are processed than when only considering the tiles on top of each other. 
With parameters aimed at good matches across the entire FOV of a tile, the diagonal cases would only rarely produce enough matches to be considered since the overlap is comparatively small.

I anyway generate the same layer pairs and cross layer pairs separately with different parameter sets.

I will play with these parameters to see, whether I can split the cross layer tilepairs further in direct and diagonal neighbors and use specific parameters (including CLIP to speed up the search) for those.
