### ISSUE TITLE
matchTrial view tile order reversed

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#127]
Hi,

When I open a matchTrial with two tiles, `pRelativePosition: RIGHT`, the tile viewer shows the tile with the 'lower' ID (`q` in this case) in the right hand panel while superimposing the point matches in the reversed positions on the opposite tiles.
The `p` positions on the left border of the `q` tile (that has the 'lower' id) and vice versa.

**Comment by martinschorb** [comment]
![Screenshot 2022-01-25 at 15 11 55](https://user-images.githubusercontent.com/35071867/150992982-6c443131-9e6d-45de-a985-16e32c35cfa2.png)

**Comment by martinschorb** [comment]
If I reverse the tilespec urls and change `pRelativePosition:` to  `LEFT`, the point positions stay the same but the images swap:
![Screenshot 2022-01-25 at 15 14 38](https://user-images.githubusercontent.com/35071867/150993351-11783930-b1bf-4d4d-92ef-91baf9386277.png)

and here they match.

**Comment by martinschorb** [comment]
The same happens for TOP/BOTTOM:
![Screenshot 2022-01-25 at 17 57 40](https://user-images.githubusercontent.com/35071867/151023048-9544df58-f07c-49a6-b688-dc005733ace0.png)

**Comment by trautmane** [comment]
Hi @martinschorb - please confirm this commit fixes the problem.  If it doesn't work, make sure you aren't running with an old cached version of janelia-match-trial.js and then if it still doesn't work let me know.
