### ISSUE TITLE
Metadata of exported section images

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#132]
Hi,

I wonder if it would be possible to populate the metadata of the image files generated by `RenderSectionClient.java` and the respective section image web service API calls that seem to use

https://github.com/saalfeldlab/render/blob/ad8e2991e893ca019924609869acc156a4e8439c/render-app/src/main/java/org/janelia/alignment/Utils.java#L127

or 

https://github.com/saalfeldlab/render/blob/ad8e2991e893ca019924609869acc156a4e8439c/render-app/src/main/java/org/janelia/alignment/Utils.java#L139

by incorporating the resolution (multiplied with the inverse of the chosen scale factor).
I don't know how jpg or png can handle this but for TIFF it should be straight forward using the underlying ij library, shouldn't it?

That would make our users extremely happy to get the correct scale bar on their section exports.

Enjoy your weekend!

**Comment by trautmane** [comment]
Hi @martinschorb - this makes sense to me.  Do you happen to know specifically which tag id the tiff readers your users use need?  I'll dig around ImageJ to see if I can find it, but want to make sure I use the correct one.  I guess it would help to know how your users typically view the tiff files.

**Comment by martinschorb** [comment]
Hi @trautmane ,

I am pretty sure that all users mostly drag and drop files onto ImageJ to open them . Hence it would be the basic ImageJ file loader.
