### ISSUE TITLE
how to solve

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#133]
Hi,
I'd like to try your solver to see how it compares with Allen's BigFeta.
What's the easiest way to launch it? I could not find any documentation in it.

Would it be `class DistributedSolveMultiThread` with those parameters?

I found https://github.com/saalfeldlab/render/blob/3c01b01db9115f00c7fce2449601176a94478a18/render-ws-java-client/src/main/java/org/janelia/render/client/solver/DistributedSolveParameters.java#L38

**Comment by trautmane** [comment]
Hi @martinschorb , 

@StephanPreibisch has the multi-thread solver you found plus two Spark variants here:
https://github.com/saalfeldlab/render/tree/master/render-ws-spark-client/src/main/java/org/janelia/render/client/solver

There is also this debugger variant intended for small scale testing (though I am not sure if it is currently working):
https://github.com/saalfeldlab/render/blob/master/render-ws-java-client/src/main/java/org/janelia/render/client/solver/DistributedSolveDebugger.java

The parallelization of the solves is currently specialized for our FIBSEM data sets which have tens of thousands of z-layers but only 1 to 5 tiles per z-layer (so we parallelize by z).  We are just starting to generalize this to handle other acquisition layouts - our key motivator is to handle forthcoming multi-SEM data.  But ... we are just starting generalization and as you noted everything still needs to be documented.

If you still want to try it, here is an example of the parameters I ran with for a recent Spark solve of a FIBSEM data set:
```
--baseDataUrl http://.../render-ws/v1 
--owner flyem 
--project Z1221_05 
--stack v2_acquire 
--targetStack v2_acquire_align 
--matchCollection Z1221_05_v1 
--maxNumMatches 0 
--completeTargetStack 
--blockSize 500 
--blockOptimizerLambdasRigid 1.0,1.0,0.9,0.3,0.01 
--blockOptimizerLambdasTranslation 1.0,0.0,0.0,0.0,0.0 
--blockOptimizerIterations 1000,1000,500,250,250 
--blockMaxPlateauWidth 250,250,150,100,100 
--maxPlateauWidthGlobal 50 
--maxIterationsGlobal 10000 
--dynamicLambdaFactor 0.0 
--threadsWorker 1 
--threadsGlobal 1
```

I'm interested in your motivation for using these solvers.
Was BigFeta not producing good results for you or were you just curious about @StephanPreibisch 's implementation?

**Comment by martinschorb** [comment]
Hi Eric,

thanks for the explanations. Happy to give feedback.

> I'm interested in your motivation for using these solvers.
> Was BigFeta not producing good results for you or were you just curious about @StephanPreibisch 's implementation?

In fact, I was trying to do exactly what you seem to have developed this solver for. Aligning FIBSEM stacks with many slices but few tiles. I could not get BigFeta to work in that scenario (single tile) and before starting to dig deep into debugging what is going wrong, I remembered having seen the solver directory when browsing the client scripts after one of your last updates.

**Comment by martinschorb** [comment]
Soving works now. I also managed to get BigFeta running. My mistake was to not assign all tilespecs a proper initial transform.
