### ISSUE TITLE
alignment creates block artifacts

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#138]
Dear all,

we noticed block artifacts in our aligned data and I could trace it to the SIFT alignment (excluding import/materialize steps).

- When we export aligned image data at scale 1.0 block/chunk artifacts are visible (like a square mesh of noise)

![612 0](https://user-images.githubusercontent.com/35071867/189950930-ae25ce9a-dfd5-4504-aad9-6f1ebbffa852.jpg)

- these are not present in the raw stack

![612 0](https://user-images.githubusercontent.com/35071867/189950902-1476fc18-1dd3-458f-b188-fc73579770af.jpg)

- we find them in all exports (n5, client slice export, API slice export)

- we use the rigid model for the SIFT pointmatch determination and during the solve step.
- we have other types of data and older alignments where the effect is not present.

here are the resolved tiles from the section and bounds shown above (aligned stack):

```JSON
{
  "transformIdToSpecMap": {},
  "tileIdToSpecMap": {
    "0000.0087.00612": {
      "tileId": "0000.0087.00612",
      "layout": {
        "sectionId": "612",
        "temca": "3View",
        "camera": "3View",
        "stageX": 17382.342746314105,
        "stageY": 61583.12137654104,
        "rotation": 95,
        "pixelsize": 8
      },
      "z": 612,
      "minX": 17368,
      "minY": 61581,
      "maxX": 23302,
      "maxY": 66033,
      "width": 6144,
      "height": 4608,
      "minIntensity": 0,
      "maxIntensity": 255,
      "mipmapLevels": {
        "0": {
          "imageUrl": "file://---g0000_t0087_s00612.tif"
        }
      },
      "transforms": {
        "type": "list",
        "specList": [
          {
            "type": "leaf",
            "className": "mpicbg.trakem2.transform.AffineModel2D",
            "dataString": "0.9654141894 0.0004752273 -0.0004752273 0.9654141894 17370.5217438190 61581.0898800188"
          }
        ]
      },
      "meshCellSize": 64
    },
    "0000.0086.00612": {
      "tileId": "0000.0086.00612",
      "layout": {
        "sectionId": "612",
        "temca": "3View",
        "camera": "3View",
        "stageX": 11538.351306236398,
        "stageY": 61583.08364754174,
        "rotation": 95,
        "pixelsize": 8
      },
      "z": 612,
      "minX": 11539,
      "minY": 61578,
      "maxX": 17492,
      "maxY": 66048,
      "width": 6144,
      "height": 4608,
      "minIntensity": 0,
      "maxIntensity": 255,
      "mipmapLevels": {
        "0": {
          "imageUrl": "file://---g0000_t0086_s00612.tif"
        }
      },
      "transforms": {
        "type": "list",
        "specList": [
          {
            "type": "leaf",
            "className": "mpicbg.trakem2.transform.AffineModel2D",
            "dataString": "0.9673090111 0.0020196070 -0.0020196070 0.9673090111 11548.8071175235 61578.6980066257"
          }
        ]
      },
      "meshCellSize": 64
    }
  }
}
```

Do you spot anything that could be the reason?

**Comment by trautmane** [comment]
Hi @martinschorb - can you email me or post here a link to the 2 source tif files in this example so that I can take a look?

Thanks,
Eric

**Comment by martinschorb** [comment]
Hi @trautmane 
here they are:
https://oc.embl.de/index.php/s/h8ksTpGYpKM39HC

The crop area shown above is the cell on the right.

Thanks for checking!

**Comment by trautmane** [comment]
Thanks @martinschorb - I'm able to render your tiles and the crop area above (which I think is actually in tile 086 instead of 087).  Can you highlight exactly where you see the square mesh of noise that does not exist in the source?  I apologize for being obtuse (happens more often then I'd care to admit :), but I'm not seeing where the the problem is.

**Comment by martinschorb** [comment]
Hi @trautmane 

it is not easy to spot. I uploaded two more images, that I exported using the API `tif-image?scale=1`. One from the original stack and one from the aligned stack. If you zoom to 100% (or more), you can see a square pattern all across the image present in the aligned stack but not the raw.

**Comment by martinschorb** [comment]
Hi @trautmane 
yes it is not very obvious in the materialized image. I have indicated a couple of lines here:
![aligned](https://user-images.githubusercontent.com/35071867/190410357-2089c6e7-e6aa-4442-92dc-70e0dda0fadc.png)

**Comment by martinschorb** [comment]
It appears in materialized tile images as well as section images after generating an aligned stack using the bigfeta solver (independent of format tif/png/jpg/n5).

**Comment by trautmane** [comment]
Thanks @martinschorb - I believe that 32-ish-pixel box pattern is actually in the source and it is "enhanced" by the pixel interpolation done when the image is slightly rotated (as occurred in your alignment).  You can see the same issue by loading tile 086 into Fiji and using Image -> Transform -> Rotate... and select an angle of 3 degrees.  You can hide the pattern a bit in render by setting `skipInterpolation=true` in the render parameters.  I'm guessing the pattern would also be hidden if you rotated the entire stack back by a few degrees after alignment.  Let me know if you disagree and I can run this by the real experts at Janelia - I easily could be misunderstanding something.

**Comment by martinschorb** [comment]
Hi @trautmane ,
you spotted this correctly. It seems that a slight in-plane rotation leads to this grid artifact. Probably, there is some periodicity in the noise pattern of the SEM scan that gets enhanced. I'll try to find out where it comes from.
