### ISSUE TITLE
render sevice connection error

### ISSUE THREAD

**Issue by elizwq** [saalfeldlab/render#139]
1."docker pull fcollman\render-python", it seems like a local docker image. could you give a pubilic image address?
2. when i follow the guide in "https://render-python.readthedocs.io/en/latest/guide/index.html#getting-started", it runs successfully until i run "renderapi.stack.create_stack(stack,render=render)". it meets an error like this:  "    raise RenderError(
renderapi.errors.RenderError: cannot post {'stackResolutionX': 1.0, 'stackResolutionY': 1.0, 'stackResolutionZ': 1.0, 'createTimestamp': '2023-40-15T11:40:26.00Z'} to http://192.168.50.10:8080/render-ws/v1/owner/myowner/project/myproject/stack/mystack with params None returned status_code 500 with message Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]"

how can i connect to it?

**Comment by trautmane** [comment]
Hi,

1. Forrest's fcollman/render-python images are publicly available on dockerhub [here](https://hub.docker.com/r/fcollman/render-python).

2. The error you posted indicates that the render web services cannot connect to the database (MongoDB) server.  Forrest posted some ideas on how to correct that problem in the [asap-modules issue](https://github.com/AllenInstitute/asap-modules/issues/248) you created just before creating this issue.  I'll try to add a little more context here to (hopefully) help ...

Architecturally, there are three key components in the system: a client (python code using the render-python library in your case), render web services, and a render database.    The render web services and database can be deployed in different ways which can make things a little confusing.

For large scale production use (as is done at Janelia and at the Allen Institute), a centralized MongoDB database is deployed separately from the web services on dedicated hardware.  This allows the web services instances to be scaled up and/or modified while still sharing the same core data in the central database.  It also allows the database to be deployed on hardware specifically sized/setup for heavy concurrent usage.  

For small scale development and/or exploration, you can deploy the web services and database as separate containers within a swarm using docker compose as [Forrest suggested here](https://github.com/AllenInstitute/render-python/blob/master/docker-compose.yml).  There are also other small scale deployment options [documented here](https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws.md).  One thing to keep in mind when using docker based database deployments is that the containers are by default ephemeral, so when you shut down the the database container its data will be lost. 

Let me know how things go ...

Best,
Eric
