### ISSUE TITLE
JAVA_HOME should point to a JDK not a JRE

### ISSUE THREAD

**Issue by hasansaeedkia** [saalfeldlab/render#143]
Hi dears 
I want to use Rander Web Services , i do it step by step exactly like this link :
https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws.md
but , an error occur when i want to do step 4 , i maen Build the Rander Modules , 
and the error is  :

The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

What should I do?

**Comment by hasansaeedkia** [comment]
> Hi dears I want to use Rander Web Services , i do it step by step exactly like this link : https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws.md but , an error occur when i want to do step 4 , i maen Build the Rander Modules , and the error is :
> 
> The JAVA_HOME environment variable is not defined correctly This environment variable is needed to run this program NB: JAVA_HOME should point to a JDK not a JRE
> 
> What should I do?

**Comment by trautmane** [comment]
Hi @hasansaeedkia - apologies for my delayed response.
I'm assuming you resolved your problem because you closed the issue.
If you still need help, let me know here,
Eric
