### ISSUE TITLE
add feature to enable server side checking of tile existence

### ISSUE THREAD

**Issue by fcollman** [saalfeldlab/render#33]
It would be useful for us to be able to check that the render service can actually read a tile in a tilespec, without having to actually render it.

**Comment by perlman** [comment]
Would this be a "data verification" process? I would find this useful as well, e.g., to make sure replicated copies of alignments are legit.

**Comment by fcollman** [comment]
yeah we were thinking about it in the context of being able to trigger workflows based upon whether a tilespec has been created, and verifying that render can actually read the files that have been referenced in the tilespec.  We can just ask if the tilespec exists for now.

**Comment by trautmane** [comment]
Do you need this for already stored tile specs (e.g. .../tile/<tileId>/validationResult) or do you want the service to validate a spec provided by the requester?

**Comment by fcollman** [comment]
We want this for existing tiles, basically does this stack have this tileid as quickly as possible. Right now we are pulling the whole tilespec, which works but is slower than necessary.  We are using it to write pipelines that say have dependancies and outputs that are "upload" this to render. So the existence of a tilespec means that step completed.
