### ISSUE TITLE
Override tilespec attributes at render time (specifically, minIntensity and maxIntensity)

### ISSUE THREAD

**Issue by perlman** [saalfeldlab/render#4]
A "tilespec override" mechanism would be nice for making one-off visualization-only changes to data in the database.

The specific use case we have is to play with the minIntensity & maxIntensity values for data where they were incorrectly specified.

**Comment by fcollman** [comment]
I believe we have implemented minIntensity and maxIntensity in the latest changes that eric merged from my branch, so this should be marked as complete.
