### ISSUE TITLE
stackMetadata should track channels in stack

### ISSUE THREAD

**Issue by fcollman** [saalfeldlab/render#54]
this would be useful for visualization via ndviz/neuroglancer to allow user to select from the available channels for visualization.

**Comment by trautmane** [comment]
Fixed by https://github.com/saalfeldlab/render/commit/60d66f5a1a4940f179bff2da58cae8bb4a4be720 and https://github.com/saalfeldlab/render/commit/eb66b5f5c754b97ade23a593e112f0f37eca0b62
