### ISSUE TITLE
Amazon s3 support

### ISSUE THREAD

**Issue by perlman** [saalfeldlab/render#7]
Allow image data to be read from, and mipmaps stored to, s3 (using the Amazon SDK).

Data can be accessed from render via http.  s3 would allow access to private data, write support, and (possibly) a minor speed improvement.

**Comment by fcollman** [comment]
I believe that eric now has a working version of this, we should get his branch merged into master.

**Comment by fcollman** [comment]
This is addressed by #43

**Comment by trautmane** [comment]
I've merged in Eric P.'s additions and made a few minor tweaks.
