### ISSUE TITLE
default_chan option for multi-channel stacks

### ISSUE THREAD

**Issue by fcollman** [saalfeldlab/render#90]
right now the multichannel support takes the first channel in the tilespec to render when there is no default image-pyramid defined.  I was wondering if instead the tilespec could have an options 'default_channel' option, or the stack could have a 'default_channel' metadata option that if defined would control which channel is used for rendering in cases when none is given?

Right now i have to manage adding a default channel to all my stacks, and then my modules which do image specific operations either have to remember which channel is my default channel and update the tilespec with the new image path, but either redo the work on the default image pyramid or go check based upon which imageUrl matches which is the default channel... it would be much cleaner to just leave the default image pyramid blank and only fill in channels... the only problem is that then there is some unreliable ordering of the channels lists and so which channel is first and gets displayed on default is mixed/confused.  

thoughts?

**Comment by trautmane** [comment]
I think it makes sense to add a default channel name to the stack meta data that can be used in the absence of explicit channel name(s) when rendering.  Would that work for you?

When you say 'default image-pyramid defined', are you referring to the older/original single channel tile spec format with the "mipmapLevels" element at the "root" of the tile spec?
My intent was to ultimately deprecate/retire that format and require the newer format with the root "channels" element - I think that is what you mean by "it would be much cleaner to just leave the default image pyramid blank and only fill in channels" - right?

I'm also curious about your "unreliable ordering" statement.  As long as all tile specs have channels specified in the same order, the first channel should always be the same - but maybe there is a bug or some kind of parsing "feature" I missed :).  If you have a small example, I'd be interested in it (if not, no worries).  This becomes less important if we define a stack default channel name, but I'd still need to fall back to this logic in the absence of stack default channel name.

**Comment by fcollman** [comment]
Yes.. adding it as stackmetadata would work for me.

yes, the default image pyramid i meant the original/older single channel tilespec format. I think we are on the same page here.

I don't have an example at my fingertips, but I do remember a stack where i had half the tiles in ndviz showing up with one channel and another with another, but i had used one set of code to upload all those channels.  It may have been that there was some ordering in my code that setup that tilespec that i wasn't aware of, so i'm not sure where the problem is.  However, as I think you are also saying, having explicit control via the default channel name is just strictly better.
