### ISSUE TITLE
add pair metadata variants of match retrieval APIs

### ISSUE THREAD

**Issue by trautmane** [saalfeldlab/render#93]
Dan Kapner and Matt Nichols have asked for variants of the match APIs that return canvas pair information without the detailed point match data.  At a minimum, this will reduce network traffic and client side memory requirements.  It will be interesting to see if it also improves response times.  If the count of match points is included in the summary, the point match explorer web client could use these APIs exclusively.

**Comment by mlnichols** [comment]
A potential change could be to have it stored for each tile/group as well/instead of. For large collections this could save a lot of updates and it's often a sub region that (at least I) am interested in. Should still be faster than the current status quo for the whole match.
