### ISSUE TITLE
docker build maven tests fail with latest OpenJDK

### ISSUE THREAD

**Issue by trautmane** [saalfeldlab/render#95]
Michael Brewer at St. Jude noticed that the maven tests in the docker build have recently been failing with the following error message:

Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

According to https://stackoverflow.com/questions/53010200/maven-surefire-could-not-find-forkedbooter-class this is a problem with maven's surefire plugin.  Until that gets fixed, you can work around the problem by using maven's skip tests option or by explicitly referencing an older OpenJDK ( FROM openjdk:8u171-jdk as build_environment ).  I opened this issue to remind me to circle back and verify that surefire has been fixed in a month or two.

**Comment by perlman** [comment]
Another work around, as noted in the link, is to set _JAVA_OPTIONS:

`ENV _JAVA_OPTIONS -Djdk.net.URLClassPath.disableClassPathURLCheck=true`

**Comment by perlman** [comment]
The OpenJDK docker image has finally been updated.  8-jdk is now [8u212-jdk-stretch](https://github.com/docker-library/openjdk/blob/b8ce9eff38451de3282b2eb2bcd8b520fb95e1ce/8/jdk/Dockerfile), and can build render without the SureFire plugin errors.
